[aws]
profile = "default"

[notify.slack]
hook_url = "https://hooks.slack.com/..."
channel = "#general"
username = "Bad News Bot"

[notify.email]
sender = "foo@bar.baz"
recipient = "oh@no.com"
subject = "Oh no!"

[notify.json]
